photocreate_order.order_cart:
    path:     /order-cart
    defaults: { _controller: PhotocreateOrderBundle:Order:cart }

photocreate_order.order_cart_trimming:
    path:     /order-trimming/common-carts/{commonCartId}
    defaults: { _controller: PhotocreateOrderBundle:Order:trimming }

photocreate_order.order_form:
    path:     /order-form
    defaults: { _controller: PhotocreateOrderBundle:Order:form }

photocreate_order.order_complete:
    path:     /order-complete
    defaults: { _controller: PhotocreateOrderBundle:Order:complete }

photocreate_order.member_address_edit.form:
    path:     /order/member-address-edit/form
    defaults: { _controller: PhotocreateOrderBundle:MemberAddressEdit:form }
