services:
    # Subscriber
    photocreate_order.subscriber.order_event:
        class: Photocreate\OrderBundle\Subscriber\OrderEventSubscriber
        arguments:
            - '@photocreate_mailer.usecase.send_order_complete_mail'
            - '@photocreate_mailer.usecase.send_order_complete_mail_to_support'
            - '@photocreate_mailer.usecase.send_order_notice_mail'
        tags:
            - { name: kernel.event_subscriber }

    # Service
    photocreate_order.service.api_uri_builder:
        class: Photocreate\OrderBundle\Service\APIUriBuilder
        arguments:
            - '%photocreate_order.api.host%'
            - '%photocreate_order.api.version%'

    photocreate_order.service.order_complete_mail_sent_check:
        class: Photocreate\OrderBundle\Service\OrderCompleteMailSentCheckService
        arguments:
            - '@Session'
